// pkg/jsdeob/framework/testdata/solid_module.js
// FIXTURE: Solid.js compiled output. Markers: $DEVCOMP unique, _$insert / _$delegateEvents,
// 'solid-js' module literal.
import { createComponent } from 'solid-js';
const App = createComponent(() => null, {});
const dc = $DEVCOMP;
function helper(el, val) { _$insert(el, val); _$delegateEvents(["click"]); }

// pkg/jsdeob/framework/testdata/angular_module.js
// FIXTURE: Angular Ivy compiled output. Markers: ɵɵdefineComponent unique,
// ɵɵelement / ɵɵtext instructions, @angular/core import literal.
import { Component } from "@angular/core";
function App_Template() {
  ɵɵelement(0, "div");
  ɵɵtext(1, "ng");
}
const App = ɵɵdefineComponent({ type: function App_Type() {}, selectors: [["app-root"]] });
